### ISSUE TITLE
AwePoiPositionHelper.js not working in ios

### ISSUE THREAD

**Issue by vaishali-Bhakhar** [ezartech/AwePoiPositionHelper#3]
I am trying to load AwePoiPositionHelper.js file in ios,but it is not working.
It is not even loading that file in my app.

**Comment by wayneparrott** [comment]
DId you include the ecef.js file in your project?
Also fire up safari's webkit inspector and remote debug the app. Takes seconds to do. Look for any errors msgs on the console log. This will tell you immediately the source of the issue.

**Comment by vaishali-Bhakhar** [comment]
Yes,i have included ecef.js file and it is loading ecef.js in my app.
But it is not loading AwePoiPositionHelper.js file in my app.
it is working fine in safari, but i want to use it in my cordova application.

**Comment by vaishali-Bhakhar** [comment]
i got the problem.
let vec = new THREE.Vector2(poi.position.x,poi.position.z);
let rot = THREE.Math.degToRad(-h); 
This two lines in _applyInitialHeadingOffset function were causing problem 

So, i have changed it as,
var vec = new THREE.Vector2(poi.position.x,poi.position.z);
var rot = THREE.Math.degToRad(-h); 

This is working fine now.
